import type { Metadata } from 'next'
import { MarketingPage, Prose } from '../../_components/MarketingPage'

export const metadata: Metadata = {
  title: 'Terms of Service | Outwyn',
  description: 'The terms for using Outwyn.',
}

// Plain-language terms. Have them reviewed by someone qualified before relying
// on them with paying customers, and update LAST_UPDATED whenever they change.
const LAST_UPDATED = 'September 30, 2026'
const CONTACT_EMAIL = 'justin.tudhope@gmail.com'

export default function TermsPage() {
  return (
    <MarketingPage eyebrow="Legal" title="Terms of Service" intro={`Last updated ${LAST_UPDATED}`}>
      <Prose>
        <p>
          These terms apply when you create an account or use Outwyn. By using
          the service, you agree to them.
        </p>

        <h2>Your account</h2>
        <p>
          You are responsible for your account, for keeping your sign-in secure, and
          for what people in your organization do with it. Admins control who can
          connect mailboxes and other integrations.
        </p>

        <h2>Sending email responsibly</h2>
        <p>Outwyn sends email from mailboxes you own. You agree that you will:</p>
        <ul>
          <li>
            Follow the laws that apply to your email, such as CAN-SPAM in the United
            States and CASL in Canada, including a valid postal address and a working
            unsubscribe in every message.
          </li>
          <li>Have a lawful basis to contact the people you import, and honor opt-outs.</li>
          <li>Follow the terms of your email provider, including Microsoft 365.</li>
          <li>
            Not send deceptive content, not use purchased lists you have no right to
            use, and not try to get around sending limits or deliverability
            safeguards.
          </li>
        </ul>
        <p>We may pause sending or suspend an account that puts other customers or email providers at risk.</p>

        <h2>Your data</h2>
        <p>
          You own the leads, messages and other content you put into Outwyn. You
          give us permission to process it only to provide the service, as described
          in our <a href="/legal/privacy">Privacy Policy</a>. You are responsible for
          having the right to use the data you import.
        </p>

        <h2>AI features</h2>
        <p>
          Lead scores and drafted messages are generated by AI and can be wrong.
          Review them before relying on them. Nothing is sent without the approval
          settings you choose.
        </p>

        <h2>Plans and payment</h2>
        <p>
          Paid plans are billed as described when you subscribe. You can cancel at
          any time, and your plan stays active until the end of the paid period.
        </p>

        <h2>Availability and changes</h2>
        <p>
          We work to keep Outwyn available and reliable, but the service is
          provided &ldquo;as is&rdquo;, without guarantees of uninterrupted
          operation. We may change or improve features over time.
        </p>

        <h2>Limitation of liability</h2>
        <p>
          To the extent the law allows, Outwyn is not liable for indirect or
          consequential losses, such as lost sales or lost data, and our total
          liability is limited to the amount you paid us in the twelve months before
          the claim.
        </p>

        <h2>Ending your account</h2>
        <p>
          You can stop using Outwyn at any time. We may end or suspend access if
          these terms are broken. After an account ends, you can ask us to delete its
          data.
        </p>

        <h2>Changes to these terms</h2>
        <p>If we change these terms, we will update the date at the top of this page.</p>

        <h2>Contact</h2>
        <p>
          Questions about these terms: <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>
        </p>
      </Prose>
    </MarketingPage>
  )
}
